import Config

# Configure your database
config :phoenix_UI, Phoenix_UI.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "phoenix_ui_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :phoenix_UI, Phoenix_UIWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: 4000],
  check_origin: false,
  code_reloader: true,
  reloadable_apps: [:phoenix_UI, :pii_module],
  debug_errors: true,
  secret_key_base: "xwxuWkhsGQG5JgR3FkHitSByKBYSLb/kgooiBWTRzqecrg+PHEJBvlMFAdakva2Y",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:default, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:default, ~w(--watch)]}
  ],
  live_reload: [
    patterns: [
      ~r"lib/phoenix_UI_web/(controllers|live|components|utils)/.*(ex|heex)$",
      ~r"lib/phoenix_UI_web/templates/.*(eex)$",
      ~r"priv/static/.*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/phoenix_UI_web/(live|views)/.*(ex)$",
      # Add this line to watch the dependency for changes
      ~r"../pii_module/lib/.*(ex)$"
    ]
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Enable dev routes for dashboard and mailbox
config :phoenix_UI, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include HEEx debug annotations as HTML comments in rendered markup
  debug_heex_annotations: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false

config :phoenix, :server,
  client_timeout: 60_000,
  connect_timeout: 60_000,
  shutdown: 5000,
  graceful_shutdown: true,
  graceful_shutdown_timeout: 10_000

config :bandit, :server,
  read_timeout: 60_000,
  shutdown_timeout: 60_000,
  max_connections: 16384,
  silent_terminate_on_error: true,
  transport_options: [
    socket_opts: [:inet]
  ]

config :logger, :console,
  format: "$time $metadata[$level] $message\n",
  level: :info,
  metadata: [:request_id],
  device: :user,
  colors: [enabled: true],
  handle_sasl_reports: true,
  handle_otp_reports: true

# Suppress Bandit and ThousandIsland error logs
config :logger, :bandit, level: :warn

config :logger, :thousand_island, level: :warn

# Add Windows-specific terminal configuration
config :phoenix_UI, :terminal_config,
  shutdown_timeout: 10_000,
  handle_sigterm: true,
  handle_sigint: true,
  shell_opts: [
    raw: false,
    echo: true,
    line_or_char: :line
  ]

# Add analyzer configuration
config :phoenix_UI, :analyzer,
  # Set to false during tests
  auto_start: true
